name: Steinar.Aandal-Vanger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2972838268615305
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hindsight is the fool´s science
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3006441385950893
  lightness: 0.7492657897528261
  saturation: 0.171449878718704
  rhythmicContrast: 0.07372275413945317
purpose: []
